import React from 'react';

const colors = {
    primary: '#4a4e69',
    secondary: '#9a8c98',
    accent: '#c9ada7',
    background: '#f2e9e4',
    text: '#22223b',
    lightText: '#4a4e69',
    white: '#ffffff',
    error: '#e63946',
    success: '#2a9d8f',
    border: '#dedede'
};

const commonStyles = {
    button: {
        padding: '10px 15px',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: 'bold',
        fontSize: '1em',
        transition: 'background-color 0.2s ease',
    },
    input: {
        padding: '10px',
        border: `1px solid ${colors.border}`,
        borderRadius: '8px',
        fontSize: '1em',
        width: '100%',
        boxSizing: 'border-box' as 'border-box',
    },
    card: {
        backgroundColor: colors.white,
        borderRadius: '12px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
        padding: '20px',
        marginBottom: '20px',
    },
};

// FIX: Broadened the type of the `styles` object to correctly handle CSS keyframe definitions. The original type did not support the syntax for keyframe percentages (e.g., '0%', '100%'), causing a TypeScript error. This allows keyframe objects alongside standard `React.CSSProperties`.
export const styles: Record<string, React.CSSProperties | Record<string, React.CSSProperties>> = {
    // General
    screen: {
        padding: '20px',
    },
    success: {
        color: colors.success
    },
    
    // Header
    header: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '10px 20px',
        backgroundColor: colors.white,
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
        zIndex: 100,
        height: '60px',
        boxSizing: 'border-box',
    },
    headerTitle: {
        margin: 0,
        fontSize: '1.5em',
        color: colors.primary,
        fontWeight: 'bold',
    },
    cartIconContainer: {
        position: 'relative',
        cursor: 'pointer',
    },
    cartBadge: {
        position: 'absolute',
        top: '-8px',
        right: '-8px',
        backgroundColor: colors.accent,
        color: colors.white,
        borderRadius: '50%',
        width: '20px',
        height: '20px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: '0.8em',
        fontWeight: 'bold',
    },
    
    // Menu Screen
    categoryTitle: {
        fontSize: '1.8em',
        color: colors.primary,
        marginBottom: '20px',
        paddingBottom: '10px',
        borderBottom: `2px solid ${colors.border}`,
    },
    productGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
        gap: '16px',
        marginBottom: '24px',
    },

    // Product Card
    productCard: {
        backgroundColor: colors.white,
        borderRadius: '12px',
        overflow: 'hidden',
        boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
        display: 'flex',
        flexDirection: 'column',
    },
    productImage: {
        width: '100%',
        height: '100px',
        objectFit: 'cover',
    },
    productInfo: {
        padding: '8px',
        flexGrow: 1,
        display: 'flex',
        flexDirection: 'column',
    },
    productName: {
        margin: '0 0 5px 0',
        fontSize: '0.9em',
        color: colors.text,
        flexGrow: 1,
        minHeight: '36px', // Ensures buttons align across cards
    },
    productPrice: {
        margin: '0 0 10px 0',
        fontSize: '0.9em',
        fontWeight: 'bold',
        color: colors.primary,
    },
    addToCartButton: {
        ...commonStyles.button,
        backgroundColor: colors.primary,
        color: colors.white,
        padding: '6px 10px',
        fontSize: '0.8em',
    },

    // Daily Special Card
    specialCard: { ...commonStyles.card },
    specialHeader: { marginBottom: '15px' },
    specialTitle: { margin: 0, fontSize: '1.4em', color: colors.accent },
    specialBody: { display: 'flex', gap: '20px', alignItems: 'center' },
    specialImages: { display: 'flex', position: 'relative', width: '120px', height: '80px' },
    specialImage: { width: '80px', height: '80px', borderRadius: '8px', objectFit: 'cover', border: `3px solid ${colors.white}`, boxShadow: '0 2px 5px rgba(0,0,0,0.1)' },
    specialImageOverlap: { position: 'absolute', left: '40px' },
    specialInfo: { flex: 1 },
    specialDescription: { margin: '0 0 15px 0', color: colors.lightText },
    specialPriceContainer: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', marginBottom: '15px' },
    specialPriceItem: { fontSize: '0.9em', color: colors.lightText },
    specialPriceTotal: { fontSize: '1.1em', fontWeight: 'bold', marginTop: '5px', color: colors.primary },
    specialButton: { ...commonStyles.button, backgroundColor: colors.accent, color: colors.white },
    skeleton: {
        backgroundColor: '#e0e0e0',
        borderRadius: '4px',
        animation: 'pulse 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
    },

    // Bottom Nav
    bottomNav: {
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        display: 'flex',
        justifyContent: 'space-around',
        backgroundColor: colors.white,
        boxShadow: '0 -2px 5px rgba(0,0,0,0.05)',
        zIndex: 100,
        height: '70px',
        padding: '5px 0',
    },
    navButton: {
        background: 'none',
        border: 'none',
        cursor: 'pointer',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        color: colors.secondary,
        flex: 1,
        gap: '4px',
        fontSize: '0.8em',
        transition: 'color 0.2s',
    },
    navButtonActive: {
        color: colors.primary,
    },
    
    // Order Screen
    emptyMessage: { textAlign: 'center', color: colors.lightText, padding: '40px 20px', flexGrow: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' },
    loyaltyCard: { ...commonStyles.card, backgroundColor: colors.primary, color: colors.white },
    loyaltyPoints: { margin: 0, fontSize: '2em', fontWeight: 'bold' },
    loyaltyProgressContainer: { width: '100%', height: '10px', backgroundColor: 'rgba(255,255,255,0.3)', borderRadius: '5px', marginTop: '10px' },
    loyaltyProgressBar: { height: '100%', backgroundColor: colors.white, borderRadius: '5px' },
    orderCard: { ...commonStyles.card },
    orderHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' },
    orderId: { fontWeight: 'bold', fontSize: '1.2em', color: colors.primary },
    orderStatus: { padding: '5px 10px', borderRadius: '15px', fontSize: '0.9em', color: colors.white },
    orderStatusPlaced: { backgroundColor: '#3498db' },
    orderStatusPreparing: { backgroundColor: '#f1c40f' },
    orderStatusReady: { backgroundColor: '#2ecc71' },
    orderTime: { margin: '0 0 20px 0', color: colors.lightText },
    orderTotal: { textAlign: 'right', fontSize: '1.3em', fontWeight: 'bold', marginTop: '20px', color: colors.primary },

    // Cart Modal and common modal styles
    modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
    optionsModalContent: { backgroundColor: colors.white, borderRadius: '12px', width: '90%', maxWidth: '500px', maxHeight: '90vh', display: 'flex', flexDirection: 'column' },
    modalHeader: { padding: '15px 20px', borderBottom: `1px solid ${colors.border}`, display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    modalTitle: { margin: 0, fontSize: '1.3em', color: colors.primary },
    closeButton: { background: 'none', border: 'none', fontSize: '1.8em', cursor: 'pointer', color: colors.secondary, lineHeight: 1 },
    modalBody: { padding: '20px', overflowY: 'auto', flex: 1 },
    cartList: { listStyle: 'none', padding: 0, margin: 0 },
    cartItem: { display: 'flex', alignItems: 'center', marginBottom: '15px', paddingBottom: '15px', borderBottom: `1px solid ${colors.border}` },
    cartItemImage: { width: '60px', height: '60px', borderRadius: '8px', objectFit: 'cover', marginRight: '15px' },
    cartItemInfo: { flexGrow: 1 },
    cartItemName: { margin: '0 0 5px 0', fontWeight: 'bold' },
    cartItemOptions: { listStyle: 'disc', margin: '5px 0 0 20px', padding: 0, fontSize: '0.9em', color: colors.lightText },
    cartItemPrice: { fontWeight: 'bold', color: colors.primary },
    summaryRow: { display: 'flex', justifyContent: 'space-between', padding: '8px 0', fontSize: '1.1em' },
    cartTotal: { fontWeight: 'bold', fontSize: '1.4em', color: colors.primary, borderTop: `2px solid ${colors.border}`, paddingTop: '10px', marginTop: '10px' },
    timeSlotGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(80px, 1fr))',
        gap: '10px',
    },
    timeSlotGroupHeader: {
        marginTop: '20px',
        marginBottom: '10px',
        fontSize: '1em',
        fontWeight: 'bold',
        color: colors.lightText,
    },
    timeSlotButton: {
        padding: '10px',
        border: `1px solid ${colors.border}`,
        borderRadius: '8px',
        backgroundColor: colors.white,
        cursor: 'pointer',
        textAlign: 'center',
        transition: 'all 0.2s ease',
        color: colors.text,
    },
    timeSlotButtonActive: {
        backgroundColor: colors.primary,
        color: colors.white,
        borderColor: colors.primary,
        fontWeight: 'bold',
    },
    datePickerButton: {
        ...commonStyles.button,
        width: '100%',
        backgroundColor: colors.white,
        border: `1px solid ${colors.border}`,
        color: colors.text,
        marginBottom: '10px',
        textAlign: 'center',
    },
    datePickerButtonActive: {
        backgroundColor: colors.primary,
        color: colors.white,
        borderColor: colors.primary,
        fontWeight: 'bold',
    },

    // Product Options Modal
    optionsList: { listStyle: 'none', padding: 0, margin: 0 },
    optionsItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 0', borderBottom: `1px solid ${colors.border}` },
    optionsLabel: { display: 'flex', alignItems: 'center', cursor: 'pointer', flexGrow: 1 },
    optionsCheckbox: { marginRight: '10px', width: '20px', height: '20px' },
    optionsPrice: { color: colors.lightText },
    optionsModalFooter: { padding: '15px 20px', borderTop: `1px solid ${colors.border}`, display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    optionsModalPrice: { fontSize: '1.2em', fontWeight: 'bold', color: colors.primary },
    optionsModalButton: { ...commonStyles.button, backgroundColor: colors.primary, color: colors.white },
    
    // Admin
    adminAccessButton: { position: 'fixed', bottom: '80px', right: '20px', backgroundColor: colors.accent, color: 'white', border: 'none', borderRadius: '50px', padding: '10px 15px', boxShadow: '0 2px 8px rgba(0,0,0,0.2)', zIndex: 99 },
    adminContainer: { display: 'flex', height: '100vh', backgroundColor: '#f8f9fa' },
    adminSidebar: { width: '240px', backgroundColor: '#343a40', color: 'white', display: 'flex', flexDirection: 'column', padding: '20px' },
    adminSidebarTitle: { fontSize: '1.5em', textAlign: 'center', marginBottom: '30px' },
    adminSidebarNav: { flexGrow: 1 },
    adminSidebarButton: { display: 'flex', alignItems: 'center', gap: '10px', background: 'none', border: 'none', color: '#adb5bd', padding: '12px 15px', width: '100%', textAlign: 'left', borderRadius: '6px', cursor: 'pointer', fontSize: '1em', transition: 'background-color 0.2s, color 0.2s' },
    adminSidebarLinkActive: { backgroundColor: '#495057', color: 'white' },
    adminLogoutButton: { ...commonStyles.button, backgroundColor: 'transparent', border: '1px solid #dc3545', color: '#dc3545' },
    adminMain: { flexGrow: 1, padding: '30px', overflowY: 'auto' },
    adminHeader: { fontSize: '2em', color: '#343a40', marginBottom: '20px' },
    adminContentPlaceholder: { padding: '20px', backgroundColor: colors.white, borderRadius: '8px', textAlign: 'center', color: colors.lightText },
    adminLoginContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', backgroundColor: '#f8f9fa' },
    adminLoginBox: { padding: '40px', backgroundColor: 'white', borderRadius: '8px', boxShadow: '0 4px 15px rgba(0,0,0,0.1)', width: '350px', textAlign: 'center' },
    adminLoginTitle: { marginBottom: '20px', color: '#343a40' },
    adminInput: { ...commonStyles.input, marginBottom: '15px' },
    adminButton: { ...commonStyles.button, backgroundColor: '#007bff', color: 'white', width: '100%' },
    adminError: { color: colors.error, marginTop: '15px' },
    adminSubHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' },
    adminButtonPrimary: { ...commonStyles.button, backgroundColor: '#007bff', color: 'white' },
    adminButtonSecondary: { ...commonStyles.button, backgroundColor: '#6c757d', color: 'white' },
    adminButtonDanger: { ...commonStyles.button, backgroundColor: '#dc3545', color: 'white' },
    adminTableContainer: { backgroundColor: 'white', borderRadius: '8px', boxShadow: '0 2px 5px rgba(0,0,0,0.05)', overflowX: 'auto' },
    adminTable: { width: '100%', borderCollapse: 'collapse' },
    adminTh: { padding: '15px', textAlign: 'left', borderBottom: '2px solid #dee2e6', backgroundColor: '#f8f9fa', fontWeight: 'bold' },
    adminTd: { padding: '15px', textAlign: 'left', borderBottom: '1px solid #dee2e6' },
    adminProductImage: { width: '50px', height: '50px', borderRadius: '4px', objectFit: 'cover' },
    adminActionsCell: { display: 'flex', gap: '10px' },
    adminModalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1001 },
    adminModalContent: { backgroundColor: 'white', borderRadius: '8px', width: '90%', maxWidth: '600px', maxHeight: '90vh', display: 'flex', flexDirection: 'column' },
    adminModalHeader: { padding: '15px 20px', borderBottom: '1px solid #e9ecef' },
    adminModalTitle: { margin: 0, fontSize: '1.25em' },
    adminForm: { padding: '20px', overflowY: 'auto' },
    adminFormGroup: { marginBottom: '20px' },
    adminLabel: { display: 'block', marginBottom: '8px', fontWeight: 'bold', color: '#495057' },
    adminFormInput: { ...commonStyles.input },
    optionsCheckboxGroup: { display: 'flex', flexDirection: 'column', gap: '8px' },
    optionsCheckboxLabel: { display: 'flex', alignItems: 'center', gap: '8px' },
    adminFormActions: { display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '20px' },
    adminFormCard: { ...commonStyles.card, padding: '25px', marginBottom: '25px' },

    // SETTINGS MANAGER
    settingsHelperText: {
        fontSize: '0.9em',
        color: colors.lightText,
        marginTop: '-10px',
        marginBottom: '20px',
    },
    settingsMasterToggle: {
        paddingTop: '20px',
        marginTop: '20px',
        borderTop: '1px solid #e9ecef',
        display: 'flex',
        justifyContent: 'center'
    },
    settingsToggle: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
    },
    settingsToggleLabel: {
        fontWeight: 'bold',
        color: '#495057',
    },
    settingsToggleSwitch: {
        position: 'relative',
        display: 'inline-block',
        width: '50px',
        height: '28px',
    },
    settingsToggleInput: {
        opacity: 0,
        width: 0,
        height: 0,
    },
    settingsToggleSlider: {
        position: 'absolute',
        cursor: 'pointer',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#ccc',
        transition: '.4s',
        borderRadius: '28px',
    },
    settingsTable: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    settingsTh: {
        padding: '12px 15px',
        textAlign: 'left',
        borderBottom: '2px solid #dee2e6',
        backgroundColor: '#f8f9fa',
    },
    settingsTd: {
        padding: '12px 15px',
        textAlign: 'left',
        borderBottom: '1px solid #dee2e6',
        verticalAlign: 'middle',
    },
    settingsDayName: {
        textTransform: 'capitalize',
        fontWeight: 'bold',
    },
    adminFormGroupGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '20px',
    },
    
    // KITCHEN DISPLAY SYSTEM (KDS)
    kdsContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        backgroundColor: '#1f2937', // Dark background
        color: '#f9fafb',
    },
    kdsHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '15px 25px',
        backgroundColor: '#111827',
        flexShrink: 0,
    },
    kdsTitle: {
        margin: 0,
        fontSize: '1.8em',
    },
    kdsBackButton: {
        ...commonStyles.button,
        padding: '8px 15px',
        backgroundColor: '#4b5563',
        color: 'white',
    },
    kdsColumnsContainer: {
        display: 'flex',
        flex: 1,
        overflowX: 'auto',
        gap: '15px',
        padding: '15px',
    },
    kdsColumn: {
        display: 'flex',
        flexDirection: 'column',
        flex: '1 1 350px',
        minWidth: '350px',
        backgroundColor: '#374151',
        borderRadius: '8px',
    },
    kdsColumnTitle: {
        fontSize: '1.3em',
        padding: '15px',
        margin: 0,
        borderBottom: '1px solid #4b5563',
    },
    kdsColumnContent: {
        flex: 1,
        overflowY: 'auto',
        padding: '15px',
        display: 'flex',
        flexDirection: 'column',
        gap: '15px',
    },
    kdsCard: {
        backgroundColor: '#ffffff',
        borderRadius: '8px',
        padding: '15px',
        boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
        flexShrink: 0,
        border: '1px solid #e5e7eb',
    },
    kdsCardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '10px',
    },
    kdsOrderId: {
        fontWeight: 'bold',
        fontSize: '1.2em',
        color: '#1f2937',
    },
    kdsOrderTime: {
        color: '#6b7280',
        fontSize: '0.9em',
    },
    kdsCollectionTime: {
        margin: '0 0 15px 0',
        fontSize: '1.1em',
        color: '#1f2937',
    },
    kdsItemList: {
        listStyle: 'none',
        padding: 0,
        margin: 0,
        borderTop: '1px solid #e5e7eb',
        paddingTop: '10px',
    },
    kdsItem: {
        display: 'flex',
        gap: '10px',
        marginBottom: '8px',
    },
    kdsItemQuantity: {
        fontWeight: 'bold',
        color: '#1f2937',
    },
    kdsItemInfo: {
        flex: 1,
    },
    kdsItemOptions: {
        listStyle: 'disc',
        paddingLeft: '15px',
        margin: '2px 0 0 0',
        fontSize: '0.9em',
        color: '#6b7280',
    },
    kdsItemName: {
        color: '#1f2937',
    },
    kdsActionButton: {
        ...commonStyles.button,
        width: '100%',
        marginTop: '15px',
        backgroundColor: '#f59e0b',
        color: '#1f2937',
    },
    kdsActionButtonReady: {
        backgroundColor: '#22c55e',
    },
    
    // Responsive adjustments can go here if needed
    // e.g. @media (max-width: 768px) { ... }
    // But since this is JS-in-CSS, media queries are more complex to implement.
    // The current fluid layout handles most cases well.
    // ADDED FOR CATEGORY MANAGER
    categoryCard: {
        ...commonStyles.card,
        marginBottom: '25px',
    },
    categoryCardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px',
        paddingBottom: '15px',
        borderBottom: `1px solid ${colors.border}`,
    },
    categoryCardTitle: {
        margin: 0,
        fontSize: '1.4em',
        color: colors.primary,
    },
    optionsContainer: {
        display: 'flex',
        flexWrap: 'wrap' as 'wrap',
        gap: '10px',
        marginBottom: '20px',
    },
    optionChip: {
        display: 'flex',
        alignItems: 'center',
        backgroundColor: '#e9ecef',
        borderRadius: '16px',
        padding: '5px 12px',
        fontSize: '0.9em',
    },
    optionChipPrice: {
        marginLeft: '8px',
        color: '#6c757d',
        fontSize: '0.9em',
    },
    optionChipActions: {
        marginLeft: '8px',
        cursor: 'pointer',
        fontWeight: 'bold',
        color: '#6c757d',
    },
    addOptionForm: {
        display: 'flex',
        gap: '10px',
        marginTop: '20px',
        paddingTop: '20px',
        borderTop: `1px solid ${colors.border}`,
    },
    
    // ADDED FOR ORDER MANAGER
    adminOrderStatus: {
        padding: '5px 12px',
        borderRadius: '15px',
        fontSize: '0.9em',
        color: 'white',
        display: 'inline-block',
        minWidth: '100px',
        textAlign: 'center',
    },
    adminOrderStatusPlaced: { backgroundColor: '#3498db' },
    adminOrderStatusPreparing: { backgroundColor: '#f1c40f' },
    adminOrderStatusReady: { backgroundColor: '#2ecc71' },
};